version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      # Update all dependencies and devDependencies
      - dependency_type: "all"
