name: Build And Upload APK

on:
  push:
    branches:
      - master

jobs: 
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Authenticate with EAS
        run: |
          echo "{\"cli\": {\"username\": \"$EAS_USERNAME\",\"password\": \"$EAS_PASSWORD\"}}" > ~/.eas.json
          npx eas-cli login
        env:
          EAS_USERNAME: ${{ secrets.EAS_USERNAME }}
          EAS_PASSWORD: ${{ secrets.EAS_PASSWORD }}

      - name: Build the app
        run: |
          npx eas-cli build -p android

      - name: Upload the APK to Uploadcare
        run: |
          curl -F "UPLOADCARE_PUB_KEY=${{ secrets.UPLOADCARE_PUB_KEY }}" \
               -F "file=@./android/app/build/outputs/apk/release/app-release.apk" \
               "https://upload.uploadcare.com/base/"
