name: Build And Upload APK

on:
  push:
    branches:
      - master

jobs: 
  build-and-upload:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: npm install

    - name: Build the APK
      run: |
        npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/
        cd android && ./gradlew assembleRelease

    - name: Upload the APK to Uploadcare
      run: |
        curl -F "UPLOADCARE_PUB_KEY=${{ secrets.UPLOADCARE_PUB_KEY }}" \
             -F "file=@./android/app/build/outputs/apk/release/app-release.apk" \
             "https://upload.uploadcare.com/base/"
